name: CI

on:
  push:
# Can be set to specific branches
#    branches:
#      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format
        uses: ./.github/actions/format-action

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: ./.github/actions/lint-action
#      test:
#        timeout-minutes: 60
#        runs-on: ubuntu-latest
#
#        steps:
#          - name: Checkout
#            uses: actions/checkout@v3
#
#          - name: Test
#            uses: ./.github/actions/test-action

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Build
#        uses: ./.github/actions/build-action
